### ISSUE TITLE
ui.modal_remove fails unless fade is set to False

### ISSUE THREAD

**Issue by Pierre-Bartet** [posit-dev/py-shiny#1318]
In the documentation example of `ui.modal_remove`, actually trying to use it fails (the modal is never removed), unless `fade` is set to `False`.

![image](https://github.com/posit-dev/py-shiny/assets/24455641/fb9c8390-c409-48c7-9f6d-67e813eeb68e)

**Comment by gadenbuie** [comment]
Hi @Pierre-Bartet! The real culprit is `easy_close=False`. That's the argument that controls whether or not you can close the modal by clicking on the page outside the modal window. When `easy_close=False`, your app will need to either:

1. include a [ui.modal_button()](https://shiny.posit.co/py/api/core/ui.modal_button.html) to provide a button that closes the modal, or
2. programmatically close the modal on the server using [ui.modal_remove()](https://shiny.posit.co/py/api/core/ui.modal_remove.html) on the server.

The second option is less common, typically with `easy_close=False`, you'll want to add the `ui.modal_button()`. Without the modal close button, `easy_close=False` is good for blocking error messages, which could be used for situations like when a user tries to login but fails.

Here's an example ([run the app on shinylive](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxMAkhFQBXMiwkB5eXIUSAynBYsOpCXThRCZDgDc4E2RwA6EO2lQB9a0wC8Ta1igBzOE5oAG2sAEwAKOyYozw4MLjUnY1NSJwAjeTJSCLB2YgB3G3wmQo02fKYYYhCoQKYQjhriH0KASjw7FrsuiBC4GlY4Ogs6MPj5RCkZeUUmYlVxphUyNRmWbV1SCa0dPQgWxEjogAFDJPM4DD6aOBNDqJOjE3PLi3JRqbIMXLzOiGi6vpMJxhfZ3f4VdwxDCVaqBCJ-cGIwoAFU4LF46KgrEYcDybCgwj4AiEUHIFXWvguhXaCMR-1MZECcDcJRxeIJvH4gjIpOE8B0lOpYLpTBoUF6bgAYjU1jSRf8jCxsE5CIFiGspTLLMK6TRiMQKHQ3F4YTU0hksoUAMJqtatOV034ik1VM3fMIwX7dRyQsSoMKOFwcCRrIaDFpgAC+AF0gA)) using `easy_close=False` and adding the modal close button.

```python
from shiny import App, Inputs, Outputs, Session, reactive, ui

app_ui = ui.page_fluid(
    ui.input_action_button("show", "Show modal dialog"),
)


def server(input: Inputs, output: Outputs, session: Session):
    @reactive.effect
    @reactive.event(input.show)
    def _():
        m = ui.modal(
            "This is a somewhat important message.",
            title="Somewhat important message",
            fade=False,
            easy_close=False,
            footer=ui.modal_button("Close"),
        )
        ui.modal_show(m)


app = App(app_ui, server)
```

**Comment by gadenbuie** [comment]
My apologies, I missed that detail in your post -- because the code was in the screenshot, I went to the docs and tried to recreate your issue rather than being able to run your example directly.

I agree that we should have individual examples for `ui.modal_remove()` and `ui.modal_button()`. I'll take the examples from this thread and add them to our docs.

The problem with your original post is that you've included `ui.modal_show()` and `ui.modal_remove()` in the same `@reactive.effect()`. That leads to undefined behavior because you're trying to both show and remove the modal at the same time.

The idea of `modal_remove()` is that you would use a separate `@reactive.effect()` that keys off a `@reactive.event()` that's triggered within the modal UI. Here's an example ([also on shinylive](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxMAkhFQBXMiwkB5eXIUSAynBYsOpCXThRCZDgDc4E2RwA6EO2lQB9a0wC8Ta1igBzOE5oAG2sAEwAKOyYozw4MLjUnY1NSJwAjeTJSCLB2YgB3G3wmQo02fKYYYhCoQKYQjhriH0KASjw7FrsuiBC4GlY4Ogs6MPj5RCkZeUUmYlVxphUyNRmWbV1SCa0dPQgWxEjogAFDJPM4DD6aOBNDqJOjE3PLi3JRqbIMXLzOiGi6vpMJxhfZ3f4VdwxDCVaqBCJ-cGIryobIAFU4LF4mKgrEYcDybCgwj4AiEUHIFXWvgurXaCMR-2R8IZLOKYBEgVqIVIcAA-Gy6ayGV4xmREk8UoEuABrbKEQLENaFCSFADCCrWTDIbDgFSqNQwrTBLLaxoZpjIgTgbhKeIJRN4-EEZHJwngOmpyrNiJoUF6bgAYjU1oKhUwjCxsE55YrrUHAiHveCaMRiBQ6G4AHI8pO-FleGE1JzfMIwX5gh5nCyXGjXW70piVp7VuCvMjvNQYGNrPPRXr9YGghuM2KFwJOQyVCwg7oOdCQsQoxwuDgSNZDQYtMAAXwAukA)) where I've added an action link that, when clicked, removes the modal:

```python
from shiny import App, Inputs, Outputs, Session, reactive, ui

app_ui = ui.page_fluid(
    ui.input_action_button("show", "Show modal dialog"),
)


def server(input: Inputs, output: Outputs, session: Session):
    @reactive.effect
    @reactive.event(input.show)
    def _():
        m = ui.modal(
            ui.p("This is a somewhat important message."),
            ui.p(
                "All done? ",
                ui.input_action_link("close", "Close the modal.")
            ),
            title="Somewhat important message",
            fade=False,
            easy_close=False,
            footer=None
        )
        ui.modal_show(m)

    @reactive.effect
    @reactive.event(input.close)
    def _():
        ui.modal_remove()


app = App(app_ui, server)
```

**Comment by Pierre-Bartet** [comment]
Thanks for the explanation!

> That leads to undefined behavior because you're trying to both show and remove the modal at the same time.

I thought that first but was then confused by the weird interaction with fading.
Thanks.

**Comment by corey-dawson** [comment]
I have also seen issues where a modal fails to close based on ui.modal_remove(). In my case, the modal contains a loading icon while data is processed via a model. It is hard to provide an example because it seems intermittent where the modal doesnt close. However, I dont want the user be able to click off the dialog and close the loading bar when the processing is happening so easy_close should be false. My temporary fix has been to add a sleep after the function before the ui.modal_remove is called

```python
@reactive.effect
@reactive.event(input.btn_run_model)
def runModel():
  data = v_data()
  m = get_loading_modal("Running Model")
  ui.modal_show(m, session=session)
  results = run_model(data)
  v_results.set(results)
  ui.modal_remove(session=session)
  
```

**Comment by gadenbuie** [comment]
Thanks @corey-dawson. My guess is that as long as `run_model()` takes _long enough_, the modal is shown and then hidden correctly. But when `run_model()` is fast, both `ui.modal_show()` and `ui.modal_remove()` are called in the same reactive tick, i.e. both messages are sent to the server at the same time.

Here's a complete example ([also on shinylive](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACMuuAHQm4DNHiMFgGcAFjQjYWdBsxaM4UQuwBuXCP0EjxkjHAAeqBcOHT6TVhNQBXMnnmUAJnEb3rNe8Lgmapbv4hnXnlrCAB9GGJnABsAChiobABeAEYABgw0gEpEbhZ8kTIoZjD2eBYktg4MMrhYrLyCgHdxaLgq+BqOepYAWkLislKOFgAeFgTsXIgC2ZZUKBNG-IUya0YZ2q74eoCgtlE4CKioOJzlhzWNlncMSMdT2Iu5gs4wABVDlnu4aOlTRihCASADm9lQbUW7SaUBoZAwbzwzxeVTIbSSbwASkDQd8or9EciXophNgwoRosQvEkAGKnLxImYo2a8YjECiMJIAOVIcEZzIaPCFtystjCSnYpDCACNbGRSE8wICePgWFjQiwALL46JvQXcFRhYzWaJkUyVBQSmhqDAqU7WOr6oUAAUtymtcD0vF4cGU3FdindNrganIsVF8OVgv2yu1MXq01mt3upzCYmITViZEOxweZydswAxCwoI4AFbWYSsbPtSbSGZeEiBUyODObYgsABeLmIF2NpvNIXCPzikySACZBbMLob+2aMF4yLE58IpwVkydoka4JE1LsIGAAL4AXSAA)) that demonstrates the issue:

```python
import time

from shiny import reactive
from shiny.express import input, render, ui, session


def run_model(delay=10.0):
    start_time = time.time()
    while time.time() - start_time < delay:
        pass
    return time.time()

def the_modal():
    return ui.modal(
            "The model is running, please wait.",
            title="Running model",
            easy_close=False,
            footer=None,
        )


ui.input_action_button("run", "Run Model")

v_results = reactive.value()


@reactive.effect
@reactive.event(input.run)
def runModel():
    ui.modal_show(the_modal())

    # adjust the delay in seconds down to zero
    results = run_model(delay=2)
    
    v_results.set(results)
    ui.modal_remove()
```

If you adjust the model running delay down to a small value close to or equal to zero, the modal is shown but doesn't go away. After working with this example a bit, I couldn't find a way to restructure the server logic to reliably avoid this problem.

I'm beginning to suspect that this is a subtle side-effect of the client-side `showModal` function being asynchronous while the `removeModal()` function is synchronous ([shinyapp.ts](https://github.com/rstudio/shiny/blob/950c63049b37cb3156bf134fa4ff13ad3cedee48/srcts/src/shiny/shinyapp.ts#L806-L808)). If that's the case, the upstream fix could be relatively straightforward.

**Comment by Pierre-Bartet** [comment]
I tried closing the modal in a separate effect, but the problem is still there (probably because it is still inside the same reactive tick):

``` python
@reactive.effect
@reactive.event(input.run)
def runModel():
    ui.modal_show(the_modal())
    results = run_model(delay=0)
    v_results.set(results)

@reactive.effect
@reactive.event(v_results)
def remove_modal():
    ui.modal_remove()
```

**Comment by gadenbuie** [comment]
I can't reproduce this in Shiny for R using the same app; I now think this bug is specific to Shiny for Python.

**Comment by wch** [comment]
It's possible that it's happening in Python and not R because Python sends the back-to-back messages closer together.

I dug into it a little bit and I think the problem has to do with the Bootstrap Modal component. 

I stepped through the code I noticed that when the `.modal("hide")` is called, the modal wasn't visible yet.

From https://getbootstrap.com/docs/4.0/components/modal/#methods:

> All API methods are asynchronous and start a transition. They return to the caller as soon as the transition is started but before it ends. In addition, a method call on a transitioning component will be ignored.


So one possibility is in our `.show()` method, to wait for the `shown.bs.modal` event before returning from the function, which we should be able to do because `.show()` is async.

**Comment by wch** [comment]
I looked at it a bit more, and `shown.bs.modal` is triggered only after the entire thing has faded in, which would be an unacceptable delay for stopping processing of all the client side code.

I can think of some other solutions to this, but they are kind of complicated for this small issue -- maybe it would be best to just wait for a tick before calling `modal("hide")`. (I wish we could just set a state and have the UI reflect that state, instead of doing this all imperatively!)

**Comment by Pierre-Bartet** [comment]
It seems that the problem is not there anymore (1.2.1), does it mean it is fixed now?

**Comment by gadenbuie** [comment]
I think the issue still exists. Try the app linked in https://github.com/posit-dev/py-shiny/issues/1318#issuecomment-2085437403 with `run_model(delay=0)` on line 33.

**Comment by Pierre-Bartet** [comment]
Indeed, the [example in the documentation](https://shiny.posit.co/py/api/core/ui.modal_remove.html) doesn't remove the modal when the model run fast.
Surprisingly now when `fade=False` it works even without any delay delay between the display and the removal.
The documentation is quite misleading to show such a broken feature (or the feature should be fixed).

**Comment by gadenbuie** [comment]
I've fixed this upstream but need to port the fix to Shiny for Python
